version: '3'
services:
  web:
    container_name: web-questions
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_questions
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
